---
title: "ECON 706"
---

## Course Introduction

<ul>

<li><a href="mcnab.qmd">Meet Your Instructor</a></li>
<li><a href="about.qmd">Course Objectives and Materials</a></li>

</ul>

## Module 01 – Introduction to Linear Regression

<ul>
<li><a href="mod-1-0-overview.qmd">Module 1 Overview</a></li>
<li><a href="mod-1-1-matrix.qmd">Matrix Operations</a></li>
<li><a href="mod-1-2-model.qmd">Linear Regression Models</a></li>

</ul>

## Module 02 – The Least Squares Estimator

<ul>
<li><a href="mod-2-0-overview.qmd">Module 2 Overview</a></li>
<li><a href="mod-2-1-derivation.qmd">Deriving the Least Squares Estimator</a></li>
<li><a href="mod-2-2-matrix.qmd">Matrix Operations</a></li>
<li><a href="mod-2-3-orthogonality.qmd">Orthogonality</a></li>

</ul>

## Module 03 – Partitioned Regression

<ul>
<li><a href="mod-3-0-overview.qmd">Module 3 Overview</a></li>
<li><a href="mod-3-1-orthogonal.qmd">Orthongonal Partitioned Regression</a></li>
<li><a href="mod-3-2-partitioned.qmd">Partitioned Regression</a></li>

</ul>

## Module 04 - Goodness of Fit

<ul>
<li><a href="mod-4-0-overview.qmd">Module 4 Overview</a></li>
<li><a href="mod-4-1-means.qmd">The M0 Matrix</a></li>
<li><a href="mod-4-2-rsquared.qmd">R Squared</a></li>

</ul>

## Module 05 - Least Squares Variance

<ul>
<li><a href="mod-5-0-overview.qmd">Module 5 Overview</a></li>
<li><a href="mod-5-1-unbiased.qmd">Unbiasedness of the Least Squares Estimator</a></li>
<li><a href="mod-5-2-variance.qmd">Variance of the Least Squares Estimator</a></li>
</ul>

## Module 06 - Hypothesis Testing

<ul>
<li><a href="mod-6-0-overview.qmd">Module 6 Overview</a></li>
<li><a href="mod-6-1-hypothesis.qmd">Single Hypothesis Testing</a></li>
<li><a href="mod-6-2-multiple.qmd"><Multiple Hypothesis Testing</a></li>
</ul>


## Module 07 - Heteroscedasticity

<ul>
<li><a href="mod-7-0-overview.qmd">Module 7Overview</a></li>
<li><a href="mod-7-1-heteroscedasticity.qmd">Heteroscedasticity</a></li>
</ul>

------------------------------------------------------------------------

<p>This site provides <strong>interactive and static examples</strong> for economic data analysis using R and WebR. Click on the links above to explore each module.</p>
