---
title: "Matrix Operations"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    self-contained: false     # must be false when using webr
urlcolor: blue
filters:
  - webr
execute:
  webR: true
---

```{r setup, echo = FALSE, message = FALSE}

library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(tidyquant, quietly = TRUE)

```

## Matrix Operations

This module covers the essential matrix operations required for econometrics. We begin with basic matrix creation and arithmetic, progressing to more complex operations like inversion and formal multiplication. Understanding these operations is critical as they form the backbone of the Ordinary Least Squares (OLS) estimator, which we will derive and implement both manually and using built-in R functions.

## Matrix Creation

In this example, we create two vectors that contain 4 numeric elements and form two matrices that are $(2 \times 2)$ and one matrix that is $(4 \times 1)$.

We can take a transpose of a matrix by using **t()**, so **t(m_1)** would be the transpose of matrix *m_1*.

We can use the **dim** function to obtain the dimensions of a matrix (and other elements like vectors).

The code chunk below does the following:

1.  Create numeric vectors using the **combine** function and assign to **d_1** and **d_2**

2.  Using **d_1**, create a $(2 \times 2)$ matrix

3.  Using **d_2**, create a $(2 \times 2)$ matrix

4.  Using **d_1**, create a \$(4 \times 1) matrix

5.  Use **kable** to output **m_1**

6.  Use the **transpose** function and **kable** to output **t(m_1)**

```{webr-r}

d_1 <- c(2, 4, 6, 8)
d_2 <- c(5, 15, 2, 12)

m_1 <- matrix(d_1, nrow = 2, ncol = 2)
m_2 <- matrix(d_2, nrow = 2, ncol = 2)

m_1_a <- matrix(d_1, ncol = 4, nrow = 1)

dims <- tibble(d_m1     = dim(m_1),
               d_m2     = dim(m_2),
               d_m1_a   = dim(m_1_a),
               d_t_m1_a = dim(t(m_1_a)))

kable(m_1,
      caption = "Matrix M1") 

kable(t(m_1),
      caption = "Transpose of Matrix M1") 

kable(dims,
      col.names = c('M1', 'M2', 'M_1_A', 'T(M_1_A)'),
      full_width = TRUE)
```
