---
title: "Deriving Least Squares"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    self-contained: false     # must be false when using webr
urlcolor: blue
filters:
  - webr
execute:
  webR: true
---

```{r setup, echo = FALSE, message = FALSE}

library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(tidyquant, quietly = TRUE)

```

## Least Squares

In this section, we discuss the motivation behind least squares regression before deriving the least squares estimator. We then examine the small sample properties of the least squares estimator. We explore how the dependent variable can be decomposed into **explained** and **unexplained** variation through the use of the **residual maker** and **projection** matrices.

## Notation

Define a column vector $\boldsymbol{x_k}$ such that $\boldsymbol{x_k}$ consists of $n$ observations.

Let $k \in \{1, 2, \dots, K\}$ such that $\boldsymbol{x_1}$ is the first column vector.

Let $\boldsymbol{x_2}$ be the second column vector, and so on.

Combining the column vectors for $\boldsymbol{x_k}$ yields a $(n \times K)$ matrix.

The first column of the resulting $\boldsymbol{X}$ matrix consists of a column of 1's.

The subscript $k$ refers to the k-th column of the $\boldsymbol{X}$ matrix.

The subscript $i$ refers to the i-th row of the $\boldsymbol{X}$ matrix.

The linear regression model is equal to:

$$\boldsymbol{y = X \, \beta + \epsilon}$$

$$\begin{bmatrix}
y_1 \\ y_2 \\ \vdots \\ y_n
\end{bmatrix} =
\begin{bmatrix}
x_{11} & x_{12} & \dots & x_{1K} \\
x_{21} & x_{22} & \dots & x_{2K} \\
\vdots & \vdots & \vdots & \vdots \\
x_{n1} & x_{n2} & x_{n3} & x_{nK} 
\end{bmatrix}
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\beta_4
\end{bmatrix} +
\begin{bmatrix}
\epsilon_1 \\
\epsilon_2 \\
\vdots \\
\epsilon_n
\end{bmatrix}$$

## Why Least Squares?

Assume that we wish to estimate the impact of education on workers' salaries. We specify a linear regression model where salary is a function of education and other explanatory variables or:

$$
salary = \beta_1 + \beta_2 \, education + \beta_3 \, age + \dots + \beta_k x_K + \epsilon
$$

We do not observe the **population parameters**.

We need an **algorithm** or **rule** by which we can develop **estimates** of the population parameters.

The algorithm or rule is called an **estimator**.

When we use the estimator with data, we produce estimates of the population parameters.

***What is our objective?***

We want an algorithm or rule that produces estimates that are "close" to the actual values.

In other words, we want an estimator to produce estimates that are "close" to the actual values of the dependent variable.

We can define our estimates of the population parameters as **b**.

We can define our predicted values of the dependent variable as $\hat{y}$.

Our predicted values are equal to:

$$
\hat{y} = Xb = b_1x_1 + b_2x_2 + \dots + b_k x_k
$$

And our "mistakes" or "residuals" are defined as:

$$
e = y - \hat{y} = y - Xb
$$

So, what is our **objective function**?

We could try and minimize the sum of our mistakes or:

$$
\sum_{i=1}^n = y_i - \hat{y_i} = \sum_{i = 1}^n = e_i
$$

***However, we assume that our errors are normally distributed with a mean of zero, so if we sum the residuals, we would add the positive and negative values together and they would be equal to zero.***

$$
\sum_{i=1}^n  y_i - \hat{y_i} = \sum_{i = 1}^n  e_i = 0
$$

Instead, we can square our residuals and sum the squared residuals.

This is similar to estimating the variance of a random variable where we sum the squared deviations of the variable from its mean and then divide by $N$.

$$
var(X) = \frac{1}{N}\sum_{i=1}^N (x_i - \mu_x)^2
$$

Our objective function is **the minimization of the sum of the squared residuals:**

$$
\sum_{i = 1}^n (y_i - \hat{y})^2  = \sum_{i=1}^n e_i^2
$$

The question is: how do we arrive that estimates of the population parameters that minimize the sum of the squared residuals?

## Objective Function

Let $\boldsymbol{b_0}$ be a coefficient vector consisting of sample estimates of $\boldsymbol{\beta}$ from a least squares regression.

The population regression function is:

$$\boldsymbol{y} = \boldsymbol{X\beta} + \boldsymbol{\epsilon}$$

The sample regression function is:

$$\boldsymbol{y} = \boldsymbol{X\ b_0} + \boldsymbol{e}$$

where the predicted values of the dependent variable are equal to:

$$
\boldsymbol{\hat{y}} = \boldsymbol{X \, b_o}
$$

and the residuals are equal to:

$$
\boldsymbol{e} = \boldsymbol{y - \hat{y}} = \boldsymbol{y - X \, b_0}
$$

Our objective function is the **minimization of the sum of the squared residuals**, that is, we choose $\boldsymbol{b_0}$ such that the predicted values of the dependent variable best "fit" the data.

The sum of the squared residuals when we select $\boldsymbol{b_0}$ is equal to:

$$
\boldsymbol{e_0^T \, e_0}
$$

We can now specific the objective function as:

$$min_{b0}\ S(b_0) = \boldsymbol{e_0^T e_0} = (\boldsymbol{y - \hat{y}})^T\  (\boldsymbol{y - \hat{y}})$$

$$e_0^T e_0 = (\boldsymbol{y - X\ b_0})^T\  (\boldsymbol{y - X\ b_0})$$

$$e_0^T e_0 = \boldsymbol{y^Ty - b_0^T\ X^T y - y^T\ Xb_0 + b_0^T X^T X b_0}$$ It is important to note that:

$$\boldsymbol{b_0^T X^T y} \sim (1 \times K) \times (K \times n) \times (n \times 1) \sim (1 \times 1)$$ $$\boldsymbol{y^T X b_0} \sim (1 \times n) \times (n \times K) \times (K \times 1) \sim (1 \times 1)$$

$$(\boldsymbol{b_0^T\ X^T y})^T = \boldsymbol{y^T\ X\ b_0}$$

We can substitute for $\boldsymbol{y^T\ X\ b_0}$ to obtain:

$$min_{b0}\ S(b_0) =e_0^T e_0 = \boldsymbol{y^Ty - 2b_0^T\ X^T\ y + b_0^T X^T X b_0}$$

## First Derivative

There are two useful identities that will help us in the derivation of the least squares estimator.

First, for the vectors $\boldsymbol{a}$ and $\boldsymbol{b}$, the partial derivative of $\boldsymbol{a^T}$ times $\boldsymbol{b}$ with respect to $\boldsymbol{a}$ is equal to $\boldsymbol{b}$.

$$\frac{\delta \boldsymbol{a^Tb}}{\delta \boldsymbol{a}} = \boldsymbol{b}$$

Second, if $\boldsymbol{A}$ is symmetric, then the first derivative of $\boldsymbol{b^T A b}$ with respect to $\boldsymbol{b}$ is:

$$\frac{\delta \boldsymbol{b^T A b}}{\delta \boldsymbol{b}} = 2 \boldsymbol{Ab} = 2 \boldsymbol{b^TA}$$

We can now return to the task at hand. We need to take the first derivative of the objective function with respect to $\boldsymbol{b_0}$ and set the first derivative equal to zero or:

$$\frac{\partial(\boldsymbol{e_0^T e_0 )}}{\partial\ \boldsymbol{b_0}} = 0$$

$$\frac{\partial(\boldsymbol{e_0^T e_0 )}}{\partial\ \boldsymbol{b_0}} =\frac{\partial(\boldsymbol{y^Ty - 2b_0^T\ X^T\ y + b_0^T X^T X b_0})}{\boldsymbol{b_0}} = 0$$

$$\frac{\partial(e_0^T e_0 )}{\partial\ b_0} =\frac{\partial \,y^Ty}{\partial{b_0}} +  \frac{\partial \, 2b_0^T\ X^T\ y}{\partial b_0} + \frac{\partial \, b_0^T X^T Xb_0}{\partial \, b_0} = 0$$

Breaking the first derivative into its component parts yields:

$$\frac{\partial \,y^Ty}{\partial{b_0}} = 0 $$

$$\frac{\partial\ (-2\ \boldsymbol{b_0^T X^T y)}}{\partial\ \boldsymbol{b_0}} = -2 \boldsymbol{X^T y}$$ $$\frac{\partial\ (\boldsymbol{b_0^T X^T X b_0})}{\partial\ \boldsymbol{b_0}} = 2\ \boldsymbol{X^T X\ b_0}$$

The first derivative of the objective function is equal to: $$\frac{\partial S(\boldsymbol{b_0})}{\partial \boldsymbol{b_0}} = -2\ \boldsymbol{X^T\ y} + 2\ \boldsymbol{X^T X\ b_0} = 0$$

-   If a solution $\boldsymbol{b}$ exists, then the **normal equations** are: $$\boldsymbol{X^T\ X\ b} = \boldsymbol{X^T\ y}$$

## First Derivative

If the full column rank assumption holds, then $(\boldsymbol{X^T X})$ is square as it is $(K \times K)$ and $(\boldsymbol{X^T X})$ is also symmetric.

Furthermore, if the full column rank assumption holds, then $(\boldsymbol{X^T X})$ has an inverse and we can use the normal equations to obtain the least square estimates of the population parameters.

$$\boldsymbol{X^T\ X\ b} = \boldsymbol{X^T\ y}$$ $$\boldsymbol{b} = (\boldsymbol{X^T\ X})^{-1}\ \boldsymbol{X^T\ y}$$ - The second derivative of the objective function is equal to: $$\frac{\partial^2 S(\boldsymbol{b_0})}{\partial \boldsymbol{b_0 b_0^T}} = 2\ \boldsymbol{X^T X}$$ - $2\ \boldsymbol{X^T X}$ is only a positive definite matrix if the full column rank assumption holds.

-   The least squares solution, if the full column rank assumption holds, is unique and minimizes the sum of the squared residuals $e^Te$.
