---
title: "Module 2 Overview"
---

## Introduction

Welcome to **Module 2** of ECON 706.

In this module, we will continue our discussion of matrix operations. We will then discuss the intuition behind the least squares estimator before deriving the least squares estimator. We will explore projection and how projection helps us understand the least squares estimator. 

------------------------------------------------------------------------

## Learning Objectives

By the end of this module, you should be able to:

-   MLO 1: **Define** the notation and concepts used to construct the linear regression estimator.
-   MLO 2: **Derive** the least squares estimator.
-   MLO 3: **Identify** the core assumptions of the least squares estimator.
-   MLO 4: **Discuss** projection and the derivation of the least squares estimator.
-   MLO 5: **Apply** R and R Studio in the derivation of the least squares estimator.

------------------------------------------------------------------------

## Required Texts

Please select the links provided to access material where applicable.

-   William H. Greene. (2018). *Econometric Analysis, 8th Edition*. Available from Pearson. Chapters 2-3.

-   Rafael Irizarry. (2025). [Introduction to Data Science: Data Wrangling and Visualization with R](https://rafalab.dfci.harvard.edu/dsbook-part-1/). Chapters 1-2.

-   Hadley Wickham, Mine Cetinkaya-Rundel, and Garrett Grolemund. (2025) [R for Data Science](https://r4ds.hadley.nz/). Sections 1-19.

-   [Online R documentation](https://cran.r-project.org/manuals.html)

-   [RStudio Cheat Sheets](https://posit.co/resources/cheatsheets/)

------------------------------------------------------------------------

## Module To Do List

-   Complete the hands-on coding exercises embedded in each lesson (MLO 1, 5)\
-   Use WebR to experiment directly in your browser (MLO 1, 2, 3, 4, 5)\
-   Complete the weekly class assignment (MLO 1, 2, 3, 4, 5)\
-   Take the weekly knowledge quiz (MLO 1, 2, 3, 4, 5)\

------------------------------------------------------------------------

## Lessons in this Module

-   [2.1 – Matrix Operations](mod-2-1-matrix.qmd)\
-   [2.2 - Least Squares Derivation](mod-2-2-derivation.qmd)
-   [2.3 - R and Derivation](mod-2-3-rexamples.qmd)

------------------------------------------------------------------------

Next: Start with [**Matrix Operations**](mod-2-1-matrix.qmd).
